"""Initial tables

Revision ID: c8e426bc5e0d
Revises: f27af2494c39
Create Date: 2025-10-28 10:44:40.999735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e426bc5e0d'
down_revision: Union[str, Sequence[str], None] = 'f27af2494c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunkmeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vectorstore_name', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text',sa.String(), nullable=False),
    sa.Column('chunk_metadata', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunkmeta_vectorstore_name'), 'chunkmeta', ['vectorstore_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunkmeta_vectorstore_name'), table_name='chunkmeta')
    op.drop_table('chunkmeta')
    # ### end Alembic commands ###
