"""Initial tables

Revision ID: f27af2494c39
Revises: 2c7e0d22c7cc
Create Date: 2025-10-28 10:31:08.075193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27af2494c39'
down_revision: Union[str, Sequence[str], None] = '2c7e0d22c7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vectorstore_name', sa.String(), nullable=False),
    sa.Column('chunk_details', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_data_vectorstore_name'), 'meta_data', ['vectorstore_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_data_vectorstore_name'), table_name='meta_data')
    op.drop_table('meta_data')
    # ### end Alembic commands ###
